lib/versioneye/parsers/nuget_parser.rb, lib/versioneye/services/version_service.rb, spec/versioneye/parsers/nuget_json_parser_spec.rb, spec/versioneye/parsers/nuget_parser_spec.rb
It'll now use version_label from the file if there is no matching versions for a product;
=> #31 fix: handle cases when no matching version range;

lib/versioneye/parsers/nuget_parser.rb, spec/versioneye/parsers/nuget_parser_spec.rb
Hi,
nuget parser misses matching rule for the `[1.0,)` version range, which wasnt documented by [official docs](https://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files) but was used by many projects anyway.
I added additional parser rule and supporting test cases for my changes;
=> fix: nuget parser missed pattern for [1.0,);

lib/versioneye/parsers/nuget_parser.rb, spec/fixtures/files/nuget/onwerk_packages.config, spec/versioneye/parsers/nuget_packages_parser_spec.rb, spec/versioneye/parsers/nuget_parser_spec.rb
NotNet packages do not have always proper SemVer as Nuget spec requires.
I changed SemVer matching regex, that could match more version_groups than major.minor.patch and tested my changes against test-example Jens from Onwerk provided;
=> #257 - fix nugetParser version parser when label doesnt quite match with spec;

lib/versioneye/parsers/nuget_parser.rb, spec/versioneye/parsers/nuget_parser_spec.rb
I noticed that 1 of dependencies in the Onwerk's project in the Bitbucket issue #257 was marked outdated, but it should be green because it was fixed to latest stable version, but parser used latest and unstable version for comparison;
Old version took the latest version from the result list, but this list also included unstable versions;
I rewrite affected version_ranges to go through `VersionService.newest_version` so that filters out unstable versions now;
=> #257 - fix nugetParser; it should ignore unstable version when finding latest versions;

lib/versioneye/parsers/nuget_packages_parser.rb, lib/versioneye/parsers/nuget_parser.rb, spec/fixtures/files/nuget/onwerk_packages.config, spec/versioneye/parsers/nuget_packages_parser_spec.rb
I add support for the `allowedVersions` attribute for nuget_packages_parsers, which allows constraining version ranges for updates; more info here: [Constraining Upgrades To Allowed Versions](https://docs.nuget.org/create/versioning)
=> 40 add nuget packages parser

lib/versioneye/parsers/common_parser.rb, lib/versioneye/parsers/nuget_json_parser.rb, spec/fixtures/files/nuget/igor_project.json, spec/versioneye/parsers/nuget_json_parser_spec.rb
One of our user tried to parse he's [project.json](https://raw.githubusercontent.com/another-guy/ObEq/master/ObEq/project.json), but it kept showing parsing failures even JSONLinter showed it's totally valid doc.
Issue was that it included [U+FEFF](http://www.fileformat.info/info/unicode/char/feff/index.htm) character at the beginning JSON file;
I added additional helper function `clean_spaces` for the `CommonParser`, which now removes all the non-width characters and replaces various unicode spaces with ASCII space.
original issue: https://bitbucket.org/versioneye/versioneye/issues/263/issues-with-parsing-projectjson-in-net
=> Fix: NugetJSONParser failed to parse files with Unicode whitespaces and non-width characters;

lib/versioneye/parsers/nuget_packages_parser.rb, spec/versioneye/parsers/nuget_packages_parser_spec.rb
Hi,
by default the parser for `packages.config` used version comparator used during packages upgrade, but `nuget install` fetches only fixed versions;
I add simple workaround that transforms a version_label to the nuget version range used for install;
Upgrade range is too broad and VersionEye loses utility as tool to check outdated packages as all the packages will be in the range of update;
=> #42 - switch packages.config parser from upgrade comperator to install

lib/versioneye/parsers/gemfile_parser.rb, spec/versioneye/parsers/gemfile_line_parser_spec.rb
Uses the original requirement parser of Rubygems to make sure we are looking at a correct requirement.
=> Fix #51 Gemfile parser resolves wrong version with platforms array

lib/versioneye/parsers/gemfile_parser.rb, lib/versioneye/parsers/gemfilelock_parser.rb, spec/versioneye/parsers/gemfile_parser_spec.rb, spec/versioneye/parsers/gemfilelock_parser_spec.rb
Hi,
i added extra helper function for GemfileParser, which removes platform extensions from the version names;
For example nokogiri doesnt respect semantic versioning and uses `-` separator to add additional build information, instead of `+`; I took list of platform tags from their releases and the `strip_platform_exts` function removes all the matching tags from the version label;
I added testcases to proof correctness of helper function and to check correct behaviour after parsing;
=> fix for #53 - remove platform extensions from version;

.gitignore, docker-compose.yml, lib/versioneye/parsers/nuget_packages_parser.rb, lib/versioneye/parsers/nuget_parser.rb, spec/fixtures/files/nuget/packages_issue58.config, spec/versioneye/parsers/nuget_packages_parser_spec.rb, spec/versioneye/parsers/nuget_parser_spec.rb, versioneye-core.gemspec
The Bug was quite simple - it didnt used full version string for filtering, just only numerical part of it; and caused to look up stable versions after `2.2.0` when the latest stable version was `2.1.0` and all the  versions with `2.2.0` tag were pre-builds.
=> 58 fix nuget parser

lib/versioneye/parsers/nuget_parser.rb, spec/fixtures/files/nuget/issue62.nuspec, spec/versioneye/parsers/nuget_parser_spec.rb
It can now handle cases when version_label is not normalized in  the project file or database version has some additional zeroes in the minor or patch versions;
=> Fix for issue #62 - nuget parser cant find exact match when version_label is naughty

lib/versioneye/models/projectdependency.rb, lib/versioneye/parsers/godep_parser.rb, lib/versioneye/parsers/package_parser.rb, lib/versioneye/parsers/parser_strategy.rb, lib/versioneye/parsers/shrinkwrap_parser.rb, lib/versioneye/service.rb, lib/versioneye/services/project_import_service.rb, lib/versioneye/services/project_service.rb, spec/fixtures/files/npm-shrinkwrap.json, spec/versioneye/parsers/godep_parser_spec.rb, spec/versioneye/parsers/parser_strategy_spec.rb, spec/versioneye/parsers/shrinkwrap_parser_spec.rb
Hi,
i added custom parser for [npm-shrinkwrap.json](https://docs.npmjs.com/cli/shrinkwrap) by extending existing `PackageParser`.
It collects root-dependencies and all the recursive sub-dependencies. 
It's not very fast for huge project files. For example [this project file](https://github.com/CRogers/gates/blob/master/npm-shrinkwrap.json) takes ~50seconds to parse;
=> Add parser for npm-shrinkwrap.json file

lib/versioneye/parsers/cargo_parser.rb, lib/versioneye/parsers/godep_parser.rb, lib/versioneye/parsers/paket_parser.rb
I fixed issue with `CargoParser.parse_content` and fixed same issues in other parsers, which probably are not used in production at the moment.
=> fix: some parsers miss 2nd param in parse_content fn;

lib/versioneye/parsers/cargo_parser.rb, spec/versioneye/parsers/cargo_parser_spec.rb
It adds additional test cases to check correctness of:
* it uses original versionlabel if no product
* it parses correctly `^0.3` and skips version `0.4.0`
* it parses correctly `^0.3` and makes sure that latest release `0.3.15` is not marked as outdated
=> Add additional testcases for the `CargoParser`

lib/versioneye-core.rb, lib/versioneye/models/project.rb, lib/versioneye/parsers/jspm_parser.rb, lib/versioneye/parsers/package_parser.rb, lib/versioneye/parsers/shrinkwrap_parser.rb, lib/versioneye/service.rb, lib/versioneye/services/version_service.rb, spec/fixtures/files/npm/package_jspm.json, spec/fixtures/files/npm/package_jspm_child.json, spec/versioneye/parsers/jspm_parser_spec.rb, spec/versioneye/parsers/package_with_jspm_child_spec.rb
Hi,
i added initial support for [JSPM](http://jspm.io). Current version supports only `npm` dependencies, as there's no crawlers got git-deps or `jspm` registry;
As JSPM is sub-document of `Package.json` file, then i extended existing `PackageParser`, which will save `JSPM` dependencies into child-project.
I also find one failing tests for Rust's `CargoParser`.
* [issue on bitbucket ](https://bitbucket.org/versioneye/versioneye/issues/134/support-jspm-package-manager#comment-36757858)
=> Add initial version of jspm parser

lib/versioneye/parsers/common_parser.rb, lib/versioneye/parsers/csproj_parser.rb, lib/versioneye/parsers/nuget_parser.rb, lib/versioneye/parsers/parser_strategy.rb, lib/versioneye/service.rb, lib/versioneye/services/project_import_service.rb, lib/versioneye/services/project_service.rb, spec/fixtures/files/nuget/test.csproj, spec/versioneye/parsers/csproj_parser_spec.rb, spec/versioneye/parsers/parser_strategy_spec.rb, spec/versioneye/services/project_service_spec.rb
Hi, 
i added support for `*.csproj` files by extending existing `NugetParser`.
This PR solves the issue#379 on bitbucket: [https://bitbucket.org/versioneye/versioneye/issues/379/support-for-nuget-packages-from-csproj](https://bitbucket.org/versioneye/versioneye/issues/379/support-for-nuget-packages-from-csproj)
=> Add csproj parser

lib/versioneye/parsers/nuget_parser.rb, spec/versioneye/parsers/nuget_parser_spec.rb
Hi,
Nuget supports now wildcard versions, which they call "fluid versions". Here's the [doc](https://docs.microsoft.com/en-gb/nuget/consume-packages/dependency-resolution#floating-versions)
This PR adds support for wildcarded versions and refactors initialization of the `Projectdependency` to use function `init_dependency` instead.
=> Update nuget parser

lib/versioneye/parsers/yarn_parser.rb, spec/fixtures/files/yarn.lock, spec/versioneye/parsers/yarn_parser_spec.rb
Hi,
it's fix for [issue #388](https://bitbucket.org/versioneye/versioneye/issues/388/confusing-packages-like#comment-37230982). It was just silly error and i added test to catch the issue.
=> fix yarnParser issue when product name includes dots;

lib/versioneye/services_ext/github_webhook.rb, spec/fixtures/vcr_cassettes/github/webhooks/fetch_repo_hooks.yml, spec/versioneye/services_ext/github_webhook_spec.rb
It's required for the `rake` tasks, which could update save old project hooks in our DB;
=> add method to fetch all github hooks registered on repo;

lib/versioneye/parsers/common_parser.rb, lib/versioneye/parsers/package_lock_parser.rb, lib/versioneye/parsers/package_parser.rb, lib/versioneye/parsers/shrinkwrap_parser.rb, spec/fixtures/files/npm/package-lock.json, spec/versioneye/parsers/package_lock_parser_spec.rb, spec/versioneye/parsers/package_parser_spec.rb
it solves the issue #92 in which `PackageParser.parse_requested_version` had not matching rules for git, http-tarball or filepath-tarball;
I had extra rules and updated specs for `PackageLockParser`, `PackageParser` and `ShrinkwarpParser`
=> Fix package lock parser, solves #92

lib/versioneye/parsers/jspm_parser.rb, lib/versioneye/parsers/package_lock_parser.rb, lib/versioneye/parsers/package_parser.rb, lib/versioneye/parsers/shrinkwrap_parser.rb, spec/versioneye/parsers/package_parser_dev_spec.rb, spec/versioneye/parsers/package_parser_run_dev_spec.rb, spec/versioneye/parsers/package_parser_tilde_spec.rb
Hi,
i debugged the `JspmParser` with some projects files from Github and found 2possible bugs:
* when no project.name, then it fails to concanate string and integer value of current time
* when parent project has same name as child project then it doesnt show up on web interface
Also removed deprecation warnings from all the specs of PackageParser.
=> Fix project name bugs in  jspm parser; remove deprecations warnings on specs;

lib/versioneye/parsers/composer_parser.rb, spec/fixtures/files/composer/composer.json, spec/versioneye/parsers/composer_lock_parser_spec.rb, spec/versioneye/parsers/composer_parser_spec.rb
I tried to solve the issue #95, but `ComposerParser` already implements required feature.
I just cleaned up `ComposerParser.fetch_product_for` and add extra spec for this function.
This PR also removes deprecation warnings in the specs of ComposerParser.
=> Cleanup ComposerParser and remove deprectation warnings in its specs;

lib/versioneye/models/project.rb, lib/versioneye/services/project_parse_service.rb, lib/versioneye/services/sync_service.rb, spec/fixtures/files/npm/package_with_jspm.json, spec/fixtures/files/npm/package_without_jspm.json, spec/versioneye/updater/common_updater_spec.rb
Hi,
i updated `CommonUpdater.update_old_with_new` so that it could bring JSPM children from new project to old project.
i also removed deprecation warnings on `common_updater_spec.rb` and add test case for my update.
=> fix #101 - updating package project didnt add childrens from updated project

lib/versioneye/parsers/csproj_parser.rb, spec/versioneye/parsers/csproj_parser_spec.rb
Hi,
i added custom workaround for the `CSProjParser`, it turns every version which doesnt start with the symbols `(` or `[` into `==` version range.
=> fix #97 - use fixed version as default value;

lib/versioneye/models/product.rb, spec/versioneye/models/product_spec.rb
It solves issue with unknown packages from here:https://www.versioneye.com/perl/DateTime::TimeZone/2.13 
All the unknown packages on that page are actually submodules of the `perl/perl` package.
I just added additional fallback method into the `Product.fetch_cpan` function.
=> Fix: when module doesnt exists, check it from perl submodules;

lib/versioneye/models/version.rb, lib/versioneye/parsers/package_parser.rb, spec/versioneye/parsers/package_parser_spec.rb
Hi, 
this PR ables to look up a package version by NPM dist-tag.
Behaviour of `latest` tag stays same => it only takes latest stable version.
For other dist-tags, it will take the latest unstable version.
=> solves #117 - Add support npm tags

lib/versioneye/parsers/common_parser.rb, lib/versioneye/parsers/meta_json_parser.rb, lib/versioneye/parsers/meta_yaml_parser.rb, lib/versioneye/parsers/parser_strategy.rb, lib/versioneye/service.rb, spec/fixtures/files/cpan/META.json, spec/fixtures/files/cpan/META.yml, spec/versioneye/parsers/common_parser_spec.rb, spec/versioneye/parsers/meta_json_parser_spec.rb, spec/versioneye/parsers/meta_yaml_parser_spec.rb, spec/versioneye/parsers/parser_strategy_spec.rb
Solves #120 , which now completes support for CPAN and the maintainers of Perl packages can now easily check status of dependencies by uploading their `Meta.json` or `Meta.yml` files;
=> Add parsers for CPAN Meta.json and Meta.yml files

lib/versioneye/parsers/cargo_parser.rb, lib/versioneye/parsers/composer_parser.rb, lib/versioneye/services/version_service.rb, spec/versioneye/parsers/cargo_parser_spec.rb, spec/versioneye/parsers/composer_parser_spec.rb, spec/versioneye/services/version_service_spec.rb
Hi,
one of user reported that he get got wrong results for all the caret versions in his `composer.json` project. Link to the issue: https://github.com/versioneye/versioneye/issues/713
I added tests and indeed old implementation included upper border, which should be excluded.
Then i noticed that the logic of the `caret` selector are same for `ComposerParser` and `CargoParser`, that's why i moved the `newest_caret_version` into the `VersionService` and added more additional tests for it;
So, now the caret selector should also work for ComposeParsers and has much less deprectation warnings int the specs;
=> Fix: Issue #713 composer caret

lib/versioneye/parsers/cargo_parser.rb, lib/versioneye/parsers/composer_parser.rb, lib/versioneye/parsers/package_parser.rb, lib/versioneye/services/version_service.rb, spec/versioneye/parsers/cargo_parser_spec.rb, spec/versioneye/parsers/composer_parser_spec.rb, spec/versioneye/parsers/package_parser_spec.rb, spec/versioneye/parsers/package_with_jspm_child_spec.rb, spec/versioneye/services/version_service_spec.rb
Hi,
i just noticed that the `PackageParser` uses it's own caret matching in the `parse_requested_version`,  i added tests and it was correct implementation, but it will be repeating implementation after changes for ComposerParser will be merged;
So, i made changes proactively, so we could later more easily push changes for the `PackageParser` too;
=> Cleanup npm caret matcher - NB! requires changes from Composer PR!

spec/versioneye/parsers/jspm_parser_spec.rb
I noticed that build was broken after you merged my PR;
And it was because it catched another bug in old NPMParser, which solved `^0.0.5` to `^0.0.8`, but should be `0.0.5`. I also double check the case with Node's `semver` package:
```javascript
npm install semver
node
> var semver = require('semver')
undefined
> semver.satisfies('0.0.8', '^0.0.5') 
false
```
=> fix failing jspm_parser_spec;
